disable workflow on PR draft
ComposableFi/composable pull request #1020
Opened 2022-05-18 23:06 UTC by nimboya

## Issue
*https://github.com/ComposableFi/SRE/issues/5*

## Description
*https://github.com/ComposableFi/SRE/issues/5*

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

2022-05-18 23:06 UTC, composable-sre requested changes
This pull request does not contain a valid label. Please add one of the following labels: `['major', 'minor', 'patch']`

2022-05-18 23:07 UTC, composable-sre approved these changes

2022-05-19 10:02 UTC, haroldsphinx approved these changes

2022-05-23 15:44 UTC, dzmitry-lahoda approved these changes
looks resonable

2022-05-23 15:44 UTC, composable-sre approved these changes

2022-06-20 12:39 UTC, closed without merging