[CU-2dve0nb] docs(Technical stack overview): Replaced old page with new design
ComposableFi/composable pull request #1092
Opened 2022-05-31 22:36 UTC by Martin-Kiss

## Issue
https://app.clickup.com/t/2dve0nb

## Checklist

~~- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_~~
~~- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_~~

2022-05-31 22:36 UTC, ComposableFiB0t commented
Task linked: [CU-2dve0nb mdbook changes](https://app.clickup.com/t/2dve0nb)

2022-06-06 14:57 UTC, cor submitted a review, later dismissed
Looks good, but needs some changes

2022-06-06 14:57 UTC, cor commented on book/src/products/technical-stack-overview.md
> +## **[Simplicity at Our Core: Our Guiding Principle](https://dali.devnets.composablefinance.ninja/products/technical-stack-overview.html#simplicity-at-our-core-our-guiding-principle)**
why did you make these headings links?

2022-06-06 14:57 UTC, cor commented on book/src/products/technical-stack-overview.md
> +## **Our Current Technical Stack**
You should not make `##`'s bold with `**`, as that is done automatically

2022-06-06 14:57 UTC, cor commented on book/src/products/technical-stack-overview.md
> +### **The Composable Application Layer**
You should not make `###`'s bold with `**`, as that is done automatically

2022-06-06 15:16 UTC, PoisonPhang requested changes

2022-06-06 15:16 UTC, PoisonPhang commented on book/src/products/technical-stack-overview.md
> +### The Composable Application Layer consists of applications on both our [Kusama Parachain (Picasso)](https://dali.devnets.composablefinance.ninja/products/the-picasso-parachain.html) and our [Polka
This should be a paragraph (no whole line markdown modifiers) not a heading 3

2022-06-06 15:16 UTC, PoisonPhang commented on book/src/products/technical-stack-overview.md
> +### The [Composable Cross-Chain Virtual Machine (XCVM)](https://dali.devnets.composablefinance.ninja/products/cross-chain-virtual-machine.html) is a top-level orchestration layer for deploying protoc
Should be paragraph, not heading 3

2022-06-06 15:16 UTC, PoisonPhang commented on book/src/products/technical-stack-overview.md
> +### The [Routing Layer](https://dali.devnets.composablefinance.ninja/products/routing-layer.html) is our pathway execution layer that assesses all of the possibilities for a given action (e.g taking
Should be paragraph, not heading 3

2022-06-06 19:22 UTC, PoisonPhang submitted a review, later dismissed
LGTM! To fix CI, you might need to rebase on main. 
Feel free to message me on Slack if you'd like any advice on rebasing or need a new approval afterward.

2022-06-08 18:50 UTC, 0xBrainjar2 reviewed
Please use new tech stack image jafar has

2022-06-09 14:25 UTC, PoisonPhang approved these changes

2022-06-13 19:28 UTC, PoisonPhang approved these changes

2022-06-17 10:33 UTC, KaiserKarel commented
@Martin-Kiss please rebase

2022-06-21 11:14 UTC, Martin-Kiss commented
This PR can be closed once #1180 has been merged.

2022-06-21 12:12 UTC, closed without merging

2022-06-21 12:13 UTC, Martin-Kiss commented
Redundant PR, closed.