Removed unused patches
ComposableFi/composable pull request #1206
Opened 2022-06-24 15:12 UTC by PoisonPhang

## Issue
N/A

## Description
For a while now, our unused patches have been breaking the functionality of RA. This will correct it for the meantime, but we will need to continue to evaluate which patches we have in use in the future

2022-06-24 15:38 UTC, benluelo reviewed
A comment at the top of the patch explaining why some patches are commented out would be good, otherwise lgtm

2022-06-24 15:46 UTC, dzmitry-lahoda submitted a review, later dismissed

2022-06-26 16:10 UTC, KaiserKarel requested changes
Could we, instead of commenting, plainly remove them?

2022-06-27 12:48 UTC, KaiserKarel approved these changes

2022-06-27 12:49 UTC, dzmitry-lahoda approved these changes

2022-06-27 12:49 UTC, dzmitry-lahoda commented
bors r+

2022-06-27 14:11 UTC, merged