Cu 2j4ubcg turborepo and shared fe packages mamali
ComposableFi/composable pull request #1223
Opened 2022-06-28 13:14 UTC by easteregg

## Issue
https://app.clickup.com/t/2j4ubcg

## Description
- [ ] Selecting a monorepo manager for FE applications (Turborepo)
- [ ] Refactor Pablo and Picasso to be managed by this tool.
- [ ] Bring in required private dependencies
- [ ] Update Vercel build and test runners.

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

2022-06-28 13:14 UTC, ComposableFiB0t commented
Task linked: [CU-2j4ubcg Turborepo and shared FE packages](https://app.clickup.com/t/2j4ubcg)

2022-07-05 13:17 UTC, KaiserKarel commented on .github/CODEOWNERS
> +.github/workflows/frontend-picasso-tests.yml @ComposableFi/blockchain-integrations
Would still want SRE to be an owner as well, as workflow files allow access to secrets.

2022-07-05 13:18 UTC, KaiserKarel requested changes
Please add @ComposableFi/SRE to the workflow codeowners.

2022-07-13 13:44 UTC, KaiserKarel approved these changes

2022-07-13 14:07 UTC, KaiserKarel approved these changes

2022-07-17 08:30 UTC, merged