Added Airdrop to dali runtime
ComposableFi/composable pull request #1266
Opened 2022-07-05 16:29 UTC by PoisonPhang

## Issue
Blocking #2g9jvc9

## Description
Added Airdrop to the dali runtime. Needs benchmarks

2022-07-05 16:29 UTC, ComposableFiB0t commented
Task linked: [CU-2g9jvc9 Airdrop pallet](https://app.clickup.com/t/2g9jvc9)

2022-07-06 14:33 UTC, benluelo commented on runtime/dali/src/weights/airdrop.rs
> +/// Weight functions for `bonded_finance`.
```suggestion
/// Weight functions for `airdrop`.
```

2022-07-06 14:40 UTC, PoisonPhang commented on runtime/dali/src/weights/airdrop.rs
> +/// Weight functions for `bonded_finance`.
3b831088f9ff792e8a53a4daf1e8c958e37a3982

2022-07-08 07:19 UTC, KaiserKarel commented on runtime/dali/src/weights/airdrop.rs
> +	}
Seems like we still need to get this benchmarked?

2022-07-08 07:20 UTC, KaiserKarel requested changes
Needs benchmarking?

2022-07-11 14:45 UTC, PoisonPhang commented
> Needs benchmarking?

It will. Going to address fixes before requesting benchmarks again

2022-08-15 14:32 UTC, PoisonPhang commented
Closing for now while Airdrop is in the backlog

2022-08-15 14:32 UTC, closed without merging