Update ibc dependency
ComposableFi/composable pull request #1289
Opened 2022-07-07 22:16 UTC by benluelo

## Issue

Updates the ibc dependencies to point to an existing revision.

2022-07-07 22:20 UTC, andor0 approved these changes

2022-07-07 22:20 UTC, Dom-Roth submitted a review, later dismissed

2022-07-08 06:53 UTC, KaiserKarel approved these changes

2022-07-08 07:17 UTC, seunlanlege requested changes
This will be merged in #1288

2022-07-08 08:07 UTC, andresmechali approved these changes

2022-07-08 09:16 UTC, closed without merging