Migrate pallet-ibc to child tries for ICS23
ComposableFi/composable pull request #1319
Opened 2022-07-13 19:28 UTC by seunlanlege

closes #951

2022-07-14 10:46 UTC, Wizdave97 requested changes
Looks good, great work

2022-07-14 10:46 UTC, Wizdave97 commented on frame/ibc/src/lib.rs
> +	pub type PacketCounter<T: Config> = StorageValue<_, u32, ValueQuery>;
This would probably not be needed, since we'll rewrite the `on_finalize` benchmark

2022-07-14 10:46 UTC, Wizdave97 commented on frame/ibc/ibc-trait/src/lib.rs
>  /// Get trie key by applying the commitment prefix to the path and scale encoding the result
```suggestion
/// Get trie key by applying the commitment prefix to the path
```

2022-07-14 12:21 UTC, seunlanlege commented
This should be ready now, last step is to rewrite the benchmarking of `on_finalize`

2022-07-15 21:42 UTC, Wizdave97 approved these changes

2022-07-16 05:18 UTC, seunlanlege commented on runtime/dali/src/weights/pallet_ibc.rs
>  	}
chef's kiss

2022-07-16 06:52 UTC, blasrodri approved these changes

2022-07-16 06:55 UTC, seunlanlege commented
bors r+

2022-07-16 06:56 UTC, merged