Latest fixes rebased
ComposableFi/composable pull request #1336
Opened 2022-07-18 08:19 UTC by saadjhk

## Issue
*Please replace this line with either a link to the ClickUp issue, or a reference to the GitHub issue.*

## Description
*Please replace this line with info that is not in the ClickUp ticket, eg: "also bumps dependency foo version"*

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

2022-07-21 19:15 UTC, Dom-Roth requested changes

2022-07-21 19:15 UTC, Dom-Roth commented on frontend/apps/pablo/defi/subsquid/auctions/helpers.ts
> +        "[fetchInitialBalance] Unable to retreive data from query"
```suggestion
        "[fetchInitialBalance] Unable to retrieve data from query"
```
nit: typo

2022-07-21 19:15 UTC, Dom-Roth commented on frontend/apps/pablo/defi/subsquid/auctions/helpers.ts
> +        "[fetchInitialBalance] Unable to retreive data from query"
```suggestion
        "[fetchInitialBalance] Unable to retrieve data from query"
```

2022-07-21 19:15 UTC, Dom-Roth commented on frontend/apps/pablo/defi/subsquid/auctions/helpers.ts
> +        "[fetchInitialBalance] Unable to retreive data from query"
```suggestion
        "[fetchInitialBalance] Unable to retrieve data from query"
```

2022-07-21 19:15 UTC, Dom-Roth commented on frontend/apps/pablo/defi/subsquid/auctions/helpers.ts
> +        "[fetchInitialBalance] Unable to retreive data from query"
```suggestion
        "[fetchInitialBalance] Unable to retrieve data from query"
```

2022-07-21 19:15 UTC, Dom-Roth commented on frontend/apps/pablo/defi/subsquid/auctions/helpers.ts
> +        "[fetchInitialBalance] Unable to retreive data from query"
```suggestion
        "[fetchInitialBalance] Unable to retrieve data from query"
```

2022-07-21 19:15 UTC, Dom-Roth commented on frontend/apps/pablo/defi/subsquid/auctions/helpers.ts
> +        "[fetchInitialBalance] Unable to retreive data from query"
```suggestion
        "[fetchInitialBalance] Unable to retrieve data from query"
```

2022-07-22 06:19 UTC, saadjhk commented on frontend/apps/pablo/components/Organisms/liquidity/RemoveForm/index.tsx
> +      // @ts-ignore
typescript doesn't pick up RPCs from @polkadot/api (augmentation) so i have manually disable them

2022-07-22 06:57 UTC, saadjhk commented
[cu-37bm0b1] [cu-3703d2d] [cu-2kre956] [cu-2nbhp47] Fixes merged here

2022-07-29 12:45 UTC, easteregg approved these changes

2022-07-29 13:34 UTC, andresmechali approved these changes

2022-07-29 18:34 UTC, saadjhk commented
bors r+

2022-08-01 09:47 UTC, vimukthi-git approved these changes

2022-08-01 10:43 UTC, Dom-Roth approved these changes

2022-08-01 10:44 UTC, saadjhk commented
bors r+

2022-08-02 05:10 UTC, saadjhk commented
bors r+

2022-08-02 09:21 UTC, saadjhk commented
bors r+

2022-08-02 12:20 UTC, saadjhk commented
bors r+

2022-08-03 05:21 UTC, saadjhk commented
bors r+

2022-08-03 08:01 UTC, Dom-Roth approved these changes

2022-08-03 09:28 UTC, saadjhk commented
bors r+

2022-08-03 10:31 UTC, easteregg approved these changes

2022-08-03 10:32 UTC, Dom-Roth approved these changes

2022-08-03 11:33 UTC, andresmechali approved these changes

2022-08-03 12:15 UTC, saadjhk commented
bors r+

2022-08-03 12:20 UTC, vimukthi-git approved these changes

2022-08-03 13:37 UTC, closed without merging