Devnet proper docker networking
ComposableFi/composable pull request #1532
Opened 2022-08-29 11:09 UTC by hussein-aitlahcen

2022-08-29 11:13 UTC, cor approved these changes
LGTM

2022-08-29 11:15 UTC, cor requested changes
`devnet-up` is still not workign:

` nix run "github:ComposableFi/composable/166638928088e9fb6204ce160951de8a02b35c47#devnet-up"`

> trace: warning: The check argument to evalModules is deprecated. Please set config._module.check instead.
error: getting status of '/nix/store/fykv528hph4vyb8nsfv1ijzb6ba20da4-source/.nix/services/subsquid-db.nix': No such file or directory
(use '--show-trace' to show detailed location information)

can you please fix this?

2022-08-29 11:29 UTC, andor0 commented on .nix/services/subsquid-indexer-gateway.nix
> +{ status, database, graphql-port }: {
```suggestion
{ status-service-host, database, graphql-port }: {
```

2022-08-29 11:40 UTC, andor0 approved these changes

2022-08-29 11:40 UTC, andor0 commented on scripts/polkadot-launch/network-builder.nix
> +        ++ flags;
```suggestion
        ++ builtins.filter (flag: !builtins.elem flag ["--rpc-cors=all" "--beefy" "--enable-offchain-indexing=true"]) extraFlags
```

2022-08-29 17:20 UTC, hussein-aitlahcen commented on scripts/polkadot-launch/network-builder.nix
> +        ++ flags;
Nice catch!

2022-08-29 21:56 UTC, dzmitry-lahoda approved these changes

2022-08-30 09:10 UTC, vimukthi-git approved these changes

2022-08-30 09:13 UTC, hussein-aitlahcen commented
@megifyio refresh

2022-08-30 09:13 UTC, hussein-aitlahcen commented
@mergifyio update

2022-08-30 09:42 UTC, merged