Simulate simnode
ComposableFi/composable pull request #1841
Opened 2022-10-04 20:22 UTC by haroldsphinx

- firebase deploy

2022-10-05 00:52 UTC, dzmitry-lahoda approved these changes

2022-10-05 15:22 UTC, Martin-Kiss approved these changes

2022-10-06 12:48 UTC, KaiserKarel commented on .github/workflows/docs-firebase-deploy.yml
> +name: Firebase Deploy Gcloud
```suggestion
name: Deploy Documentation
```

2022-10-06 12:49 UTC, KaiserKarel commented on .github/workflows/docs-firebase-deploy.yml
> +          echo "$(pwd)/bin" >> $GITHUB_PATH
We have/should have a nix step for this; we never manually install rust in CI, as that will lead to different versions.

2022-10-06 12:52 UTC, cor requested changes
Just run `nix build ".#composable-book"` instead of installing all of this manual tooling

2022-10-15 11:26 UTC, cor commented
Not using Nix. Closing this one in favor of including it in the next Docusaurus PR

2022-10-15 11:26 UTC, closed without merging