Aeryz/cosmwasm migrate
ComposableFi/composable pull request #1856
Opened 2022-10-05 17:51 UTC by aeryz

## Description
* Add `migrate` extrinsic for contract migration.
* Add `migrate` entrypoint to all of the cosmwasm contracts as well as CONTRACT_VERSION and NAMES to make sure that migration is securely done.
* Use `CodeIdentifier` instead of code id to make users able to use code hash if they want to for example batch instantiate + execute or migrate calls. This way they would be able to identify the code in-front.

## Checklist

- [X] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [X] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

2022-10-06 12:10 UTC, KaiserKarel commented on code/parachain/frame/cosmwasm/src/lib.rs
> +		}
Nit: this pattern allows for incorrectly migrating a contract. Instead we could use a Migrator struct, using Typestate to ensure that `migrate_phase1` is called before a contract is migrated.

2022-10-06 12:10 UTC, KaiserKarel commented on code/parachain/frame/cosmwasm/src/lib.rs
> +		}
Nit: this pattern allows for incorrectly migrating a contract. Instead we could use a Migrator struct, using Typestate to ensure that `migrate_phase1` is called before a contract is migrated.

2022-10-06 12:11 UTC, KaiserKarel commented on code/parachain/frame/cosmwasm/src/lib.rs
> +		}
In general, let's avoid patterns where foo_1 needs to be called before foo, and encode that logic in the type system.

2022-10-06 12:12 UTC, KaiserKarel requested changes
Still needs benchmarks

2022-10-18 18:15 UTC, dzmitry-lahoda commented on code/xcvm/cosmwasm/contracts/asset-registry/src/contract.rs
> +pub fn migrate(deps: DepsMut, _env: Env, _msg: MigrateMsg) -> Result<Response, ContractError> {
please add /// doc to it.

2022-10-18 18:15 UTC, dzmitry-lahoda approved these changes

2022-10-19 10:41 UTC, KaiserKarel approved these changes

2022-10-19 14:35 UTC, Martin-Kiss commented on code/parachain/frame/cosmwasm/src/lib.rs
> +				// Modify the exising `code_id`'s states and unreserve the bonded funds.
```suggestion
				// Modify the existing `code_id`'s states and unreserve the bonded funds.
```
Nit spelling; failing spellcheck CI

2022-10-19 18:40 UTC, merged