fix XCVM SPEC layout
ComposableFi/composable pull request #1863
Opened 2022-10-06 09:23 UTC by dzmitry-lahoda

Signed-off-by: Dzmitry Lahoda <dzmitry@lahoda.pro>

## Issue
*Please replace this line with either a link to the ClickUp issue, or a reference to the GitHub issue.*

## Description
*Please replace this line with info that is not in the ClickUp ticket, eg: "also bumps dependency foo version"*

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

2022-10-06 10:14 UTC, aeryz requested changes

2022-10-06 10:14 UTC, aeryz commented on code/xcvm/SPEC.md
> +fn swap(amount: u256, pair: (u128, u128), to: AccountId) { .A.. }
I think this 'A' is added accidentally

2022-10-06 17:00 UTC, hussein-aitlahcen approved these changes

2022-10-06 17:23 UTC, dzmitry-lahoda commented
it has crazy failure
```
Download action repository 'actions/checkout@v3' (SHA:2541b1294d2704b0964813337f33b291d3f8596b)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/_work/_actions/_temp_4a9f6896-9470-4d5f-84cf-6[24](https://github.com/ComposableFi/composable/actions/runs/3196350168/jobs/5218635604#step:1:25)cc7260a03/e5526187-dc86-4912-b017-de8ae29699e2.tar.gz. return code: 2.
```
retried 2 times already

2022-10-07 10:36 UTC, dzmitry-lahoda commented
@Mergifyio refresh

2022-10-07 16:04 UTC, dzmitry-lahoda commented
dozens of failures, but he just wanted only his simple 
```
fatal: unable to access 'https://github.com/composablefi/ics23/': Empty reply from server
error: program 'git' failed with exit code 128
````

2022-10-07 16:29 UTC, KaiserKarel commented
@mergifyio refresh

2022-10-10 11:50 UTC, dzmitry-lahoda commented
@Mergifyio refresh

2022-10-10 13:20 UTC, merged