[CU-33zbdbb] - use total_issuance
ComposableFi/composable pull request #1922
Opened 2022-10-10 11:57 UTC by andresmechali

## Issue
https://app.clickup.com/t/33zbdbb

2022-10-10 11:57 UTC, ComposableFiB0t commented
Task linked: [CU-33zbdbb Use `Inspect::total_issuance` instead of `RewardPool.total_shares`](https://app.clickup.com/t/33zbdbb)

2022-10-10 14:24 UTC, benluelo requested changes

2022-10-10 14:24 UTC, benluelo commented on code/parachain/frame/staking-rewards/src/lib.rs
> +					defensive!();
should add a message in the macro or a comment explaining why this is here

2022-10-10 14:24 UTC, benluelo commented on code/parachain/frame/staking-rewards/src/test/mod.rs
> +		mint_assets([BOB], [XPICA::ID], XPICA::units(200));
you should not be minting any xtokens in the tests, xtokens are only to be minted by the pallet

2022-10-10 14:35 UTC, PoisonPhang approved these changes
LGTM
However, we should remember that this partially depends on #1857 to ensure that the Share Asset is only controlled by pallet staking rewards.

2022-10-10 17:15 UTC, vimukthi-git approved these changes
LGTM

2022-10-10 17:15 UTC, vimukthi-git commented on code/parachain/frame/staking-rewards/src/lib.rs
> +			T::Assets::set_lock(T::LockId::get(), share_asset_id, fnft_account, awarded_shares)?;
:+1:

2022-10-12 10:21 UTC, andresmechali commented
@mergify refresh

2022-10-12 17:16 UTC, merged