feat(xcvm): ibc integration spec
ComposableFi/composable pull request #2198
Opened 2022-11-04 12:42 UTC by hussein-aitlahcen

2022-11-04 12:44 UTC, KaiserKarel approved these changes

2022-11-04 12:57 UTC, aeryz requested changes
I think it clearly defines all the necessary steps to add support for IBC :):)

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +layer agnostic. One of it's execution layer is CosmWasm and one of it's
```suggestion
layer agnostic. One of it's execution layers is CosmWasm and one of it's
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +transport layer is IBC. CosmWasm is IBC native and provide facilities
```suggestion
transport layers is IBC. CosmWasm is IBC native and provide facilities
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +(functions, metadatas) to leverage IBC in cross-chain communications. We support
Plural of data is also data.
```suggestion
(functions, metadata) to leverage IBC in cross-chain communications. We support
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +implement the host functions and instantiate the abstract VM to execute contracts.
```suggestion
implements the host functions and instantiates the abstract VM to execute contracts.
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +initially chose not to implements the IBC/Staking/Distribution features.
```suggestion
initially choose not to implement the IBC/Staking/Distribution features.
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +host, assumming it support IBC.
```suggestion
host, assuming it supports IBC.
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +Now that the abstract CosmWasm VM is IBC capabable, we still need to upgrade the
```suggestion
Now that the abstract CosmWasm VM is IBC capable, we still need to upgrade the
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +host to implements the extra functions required to keep satifying the interface.
```suggestion
host to implement the extra functions required to keep satifying the interface.
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +forward IBC events from the underlying VM to the IBC Pallet and call backs
```suggestion
forward IBC events from the underlying VM to the IBC Pallet and calls back
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +compatibly with our expectations, we need to tie the IBC Pallet interface with
```suggestion
compatible with our expectations, we need to tie the IBC Pallet interface with
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +mention how modules consuming IBC can be called back when events occurs (channel
```suggestion
mention how modules consuming IBC can be called back when events occur (channel
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +It is unclear how we are going to poll events from the IBC Pallet to the
```suggestion
It is unclear how we are going to poll events from the IBC Pallet to
```

2022-11-04 12:57 UTC, aeryz commented on code/xcvm/ibc/INTEGRATION.md
> +dispatch them to the according contracts. It can probably done with
```suggestion
dispatch them to the according contracts. It can be probably done with
```

2022-11-07 09:56 UTC, aeryz approved these changes

2022-11-07 12:20 UTC, merged