Update text
ComposableFi/composable pull request #2270
Opened 2022-11-11 13:53 UTC by easteregg

## Issue
https://app.clickup.com/t/31evhjc

2022-11-11 13:53 UTC, ComposableFiB0t commented
Task linked: [CU-31evhjc 5. Copywrite confirmation](https://app.clickup.com/t/31evhjc)

2022-11-11 13:59 UTC, saadjhk requested changes

2022-11-11 13:59 UTC, saadjhk commented on frontend/apps/picasso/components/Organisms/Bond/ClaimForm.tsx
> +          "An error occurred while processing the transaction. The process was canceled.",
cancelled

2022-11-11 13:59 UTC, saadjhk commented on frontend/apps/picasso/components/Organisms/Staking/BurnModal.tsx
> +              "An error occurred while processing the transaction. The process was canceled.",
cancelled

2022-11-11 13:59 UTC, saadjhk commented on frontend/apps/picasso/components/Organisms/Staking/RenewModal.tsx
> +              "An error occurred while processing the transaction. The process was canceled.",
cancelled

2022-11-11 13:59 UTC, saadjhk commented on frontend/apps/picasso/defi/polkadot/hooks/useTransfer.ts
> +              url: SUBSTRATE_NETWORKS.picasso.subscanUrl + txHash,
sir this might need a rebase

2022-11-14 07:41 UTC, easteregg commented on frontend/apps/picasso/components/Organisms/Bond/ClaimForm.tsx
> +          "An error occurred while processing the transaction. The process was canceled.",
https://www.merriam-webster.com/words-at-play/canceled-or-cancelled

2022-11-14 07:41 UTC, easteregg commented on frontend/apps/picasso/defi/polkadot/hooks/useTransfer.ts
> +              url: SUBSTRATE_NETWORKS.picasso.subscanUrl + txHash,
Rebase done.

2022-11-14 10:17 UTC, saadjhk approved these changes

2022-11-14 10:50 UTC, vimukthi-git approved these changes

2022-11-14 11:42 UTC, merged