ibc integration and test
ComposableFi/composable pull request #2431
Opened 2022-11-24 22:43 UTC by kkx

## Issue

https://app.clickup.com/t/3qvfj7v

## Additional Changes

- refactor evm SDK and create a shared lib to be used by both the interpreter and ibcBridge 
- enabled both hardhat tests and forge tests
- **we can leave `lib/forge-std` and `src/ibc` out of the review scope since they are imported and in the future will be installed and imported directly.**

## Checklist

- [ ] Updated the rust/typescript docs.
- [ ] Updated the `docs/`.

2022-11-30 11:58 UTC, aeryz requested changes

2022-11-30 11:58 UTC, aeryz commented on code/xcvm/SPEC.md
> +<AssetAmount>  ::= <AssetId> <Ratio> | <Unit>
I think this is outdated since this is changed to `<AssetId> <Balance>`

2022-11-30 11:58 UTC, aeryz commented on code/xcvm/evm/lib/forge-std/.github/workflows/tests.yml
> +name: Tests
I think we should remove the CI files

2022-11-30 11:58 UTC, aeryz commented on code/xcvm/evm/lib/forge-std/.gitignore
> +cache/
we should also remove .git files

2022-11-30 11:58 UTC, aeryz commented on code/xcvm/evm/src/libraries/SDK.sol
> +        if (field == 2) {
since we converted `AssetAmount` to have `Balance` now, I guess we should also add absolute here as well which I guess can use `handleBalance`

2022-11-30 11:58 UTC, aeryz commented on code/xcvm/evm/src/libraries/SDK.sol
> +            //self
isn't this supposed to be relayer?

2022-11-30 11:58 UTC, aeryz commented on code/xcvm/evm/src/libraries/SDK.sol
> +        } else {
one more valueType is needded for `ipRegister`

2022-11-30 12:52 UTC, aeryz approved these changes

2022-12-02 11:03 UTC, ComposableFiB0t commented
Task linked: [CU-441wwc9 Include pallet-ibc into Dali devnet](https://app.clickup.com/t/441wwc9)

2022-12-02 13:09 UTC, hussein-aitlahcen approved these changes
Let's have this one merged and refine with the spec right after the Rust side is fully stable :)

2022-12-11 20:16 UTC, merged