feat: update TOC
ComposableFi/composable pull request #2602
Opened 2022-12-07 16:49 UTC by fl-y

Updated TOC to reflect the imminent tools.xcvm.dev launch

2022-12-07 16:53 UTC, KaiserKarel approved these changes

2022-12-12 09:33 UTC, Martin-Kiss requested changes

2022-12-12 09:33 UTC, Martin-Kiss commented on docs/docs/faqs/terms-of-use.md
>  As of November 16, 2022
Should the "as of" -date be adjusted to reflect this change?

2022-12-13 12:10 UTC, andyjsbell approved these changes
thanks @fl-y

2022-12-13 14:18 UTC, merged