NX-33 - Part 1
ComposableFi/composable pull request #2721
Opened 2022-12-14 20:11 UTC by cor

2022-12-14 20:11 UTC, ComposableFiB0t commented
Task linked: [NX-33 Cleanup of the flake-parts structure](https://app.clickup.com/t/20465559/NX-33)

2022-12-14 23:24 UTC, vimukthi-git commented
sir is there any chance that things could break for v2.10004 testing and release with this in the coming days? If so I recommend delaying refactorings to build process to once v2 runtime upgrade is done.

2022-12-15 01:23 UTC, dzmitry-lahoda commented
yeah, and hopefully after zn release. also, i do not thing that 2 points from plan are good. and another one co trovercial.

2022-12-15 01:24 UTC, dzmitry-lahoda requested changes
please align changes in time and space. i mean for releases and that changes are proper(not waste)

2022-12-15 10:02 UTC, KaiserKarel commented
> sir is there any chance that things could break for v2.10004 testing and release with this in the coming days? If so I recommend delaying refactorings to build process to once v2 runtime upgrade is done.

It shouldn't, as this just moves existing files around, but @cor we can keep this in draft until tuesday to avoid any issues. :)

2022-12-15 11:26 UTC, cor commented
The hashes of the outputs remain identical, but if this scares people then sure lets wait with merging it 👍

2023-01-10 20:06 UTC, dzmitry-lahoda approved these changes

2023-01-10 23:56 UTC, obsessed-cake commented on inputs/paritytech/zombienet.nix
> +            python3
```suggestion
            python3
            pkg-config
            vips
```

2023-01-10 23:56 UTC, obsessed-cake approved these changes

2023-01-11 09:55 UTC, KaiserKarel approved these changes

2023-01-11 10:29 UTC, Dom-Roth approved these changes

2023-01-11 13:00 UTC, 0xBrainjar2 approved these changes

2023-01-11 19:44 UTC, merged