[CU-862hxdae8] Add RFP for canonical stabelcoin
ComposableFi/composable pull request #2757
Opened 2022-12-19 17:18 UTC by Martin-Kiss

## Clickup Ticket
https://app.clickup.com/t/862hxdae8

## Additional Changes
none

2022-12-19 17:18 UTC, KaiserKarel commented
Task linked: [CU-862hxdae8 Add Immunefi to Gitbook](https://app.clickup.com/t/862hxdae8)

2022-12-20 15:46 UTC, 0xBrainjar2 approved these changes

2022-12-21 15:45 UTC, KaiserKarel requested changes
- Prefer using mermaid.js for diagrams of proposals to allow easier editing from contributors.
- This seems way too early to actually merge, before XCVM launch etc.
- The requirements and technical sections were written without input from tech and subsequently of very low quality for a request for concrete proposals

2022-12-23 09:08 UTC, Martin-Kiss commented
I will open a new PR with a reasonable branch name

2022-12-23 09:08 UTC, closed without merging