[PICA-34] - Upgrade to polkadot v0.9.30
ComposableFi/composable pull request #2913
Opened 2023-01-12 17:19 UTC by hussein-aitlahcen

Upgrade polkadot from v0.9.27 to v0.9.30 as a checkpoint, the in a second PR to v0.9.33 (latest version without workspace dependencies)

Require https://github.com/ComposableFi/centauri/pull/176 to be merged first.

2023-01-16 12:22 UTC, vimukthi-git approved these changes
LGTM :rocket:

2023-01-16 12:45 UTC, obsessed-cake approved these changes

2023-01-16 13:38 UTC, cor requested changes
LGTM! Just one nit, please fix the literals as per my suggestions

2023-01-16 13:38 UTC, cor commented on code/parachain/frame/assets-registry/src/weights.rs
> +		Weight::from_ref_time(10_0000)
```suggestion
		Weight::from_ref_time(100_000)
```

2023-01-16 13:38 UTC, cor commented on code/parachain/frame/assets-registry/src/weights.rs
> +		Weight::from_ref_time(10_0000)
```suggestion
		Weight::from_ref_time(100_000)
```

2023-01-16 13:38 UTC, cor commented on code/parachain/frame/assets-registry/src/weights.rs
> +		Weight::from_ref_time(10_0000)
```suggestion
		Weight::from_ref_time(100_000)
```

2023-01-16 13:51 UTC, cor approved these changes

2023-01-16 17:44 UTC, benluelo approved these changes
:rocket:

2023-01-17 13:54 UTC, KaiserKarel approved these changes

2023-01-17 14:06 UTC, aeryz approved these changes

2023-01-17 15:45 UTC, Dom-Roth approved these changes

2023-01-18 11:24 UTC, Martin-Kiss approved these changes

2023-01-18 12:27 UTC, 0xBrainjar2 approved these changes

2023-01-18 16:25 UTC, merged