[PICA-75] remove staking rewards genesis config
ComposableFi/composable pull request #2932
Opened 2023-01-16 18:00 UTC by benluelo

2023-01-16 18:20 UTC, andyjsbell requested changes
Can we get a detailed description of what this PR is attempting to achieve please, thanks 🙏

2023-01-16 18:26 UTC, andyjsbell approved these changes
Thanks @benluelo

2023-01-17 11:13 UTC, vimukthi-git commented
I can merge this, can you check tapio locally? @benluelo

2023-01-18 17:08 UTC, vimukthi-git approved these changes

2023-01-18 17:15 UTC, PoisonPhang approved these changes

2023-01-19 17:53 UTC, merged