[PICA-96] claimable amount of rewards
ComposableFi/composable pull request #2991
Opened 2023-01-24 16:23 UTC by kkast

https://app.clickup.com/t/20465559/PICA-96
add rpc into staking-rewards pallet for claimable amount of rewards

2023-01-24 16:23 UTC, KaiserKarel commented
Task linked: [PICA-96 Claimable RPC request](https://app.clickup.com/t/20465559/PICA-96)

2023-01-24 18:33 UTC, KaiserKarel approved these changes

2023-01-24 18:41 UTC, benluelo requested changes

2023-01-24 18:41 UTC, benluelo commented on code/parachain/frame/staking-rewards/rpc/src/lib.rs
> +	fn get_claimable_amount(
The get_ prefix can be removed

2023-01-25 18:03 UTC, benluelo commented on code/parachain/frame/staking-rewards/rpc/src/lib.rs
> +	#[method(name = "stakingRewards_getClaimableAmount")]
rename this as well

2023-01-25 18:16 UTC, vimukthi-git approved these changes
LGTM :rocket:

2023-01-26 18:17 UTC, benluelo approved these changes

2023-01-26 18:27 UTC, vimukthi-git approved these changes

2023-01-26 20:11 UTC, kkast commented
@mergify refresh

2023-01-26 22:38 UTC, merged