CU-1kjdgd6 - simple proptest tutorial
ComposableFi/composable pull request #318
Opened 2021-11-25 10:30 UTC by hussein-aitlahcen

Little tutorial/documentation on the usage of proptest

2021-11-25 10:30 UTC, ComposableFiB0t commented
Task linked: [CU-1kjdgd6 Simple proptest tutorial](https://app.clickup.com/t/1kjdgd6)

2021-11-25 11:22 UTC, Br1ght0ne requested changes
Besides correcting some nits, content LGTM.

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +Most of the time, we, developers, are used to a wide variety of tests flavor
```suggestion
Most of the time, we, developers, are used to a wide variety of tests flavors
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +The idea here would be find properties that our code should held and then use
```suggestion
The idea here would be to find properties that our code should hold and then use
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +likely implement them using arbitrary, usually well known values, they lose the
```suggestion
likely implement them using arbitrary, usually well-known values, they lose the
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +However, to generalize this ideas over arbitrary projects, we will try to stay a bit abstract.
```suggestion
However, to generalize these ideas over arbitrary projects, we will try to stay a bit abstract.
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +are working on. The Vault allow strategies to operate on users funds. Users are
```suggestion
are working on. The Vault allows strategies to operate on users' funds. Users are
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +of the vault. They later can withdraw using theses LPs. Usually, this kind of
```suggestion
of the vault. They later can withdraw using these LPs. Usually, this kind of
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +protocols purpose is to have a better capital efficiency and optimize APY over
```suggestion
protocol's purpose is to have a better capital efficiency and optimize APY over
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +One of the easiest property here is the fact that `withdraw . deposit =
```suggestion
One of the easiest properties here is the fact that `withdraw . deposit =
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +identity`. This mean that if a user **deposit** and then **withdraw**, the vault
```suggestion
identity`. This means that if a user **deposit** and then **withdraw**, the vault
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +**amount** is not part of the equation, which allow us to basically generate any
```suggestion
**amount** is not part of the equation, which allows us to generate any
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +this is not always the case (it should probably be enforced but in practice we
```suggestion
this is not always the case (it should probably be enforced but in practice, we
```

2021-11-25 11:22 UTC, Br1ght0ne commented on docs/proptest.md
> +This small introduction is not meant to fully cover propest but rather to give a quick and practical overview of it's feature. To learn more about it, you should probably read [the proptest documenta
```suggestion
This small introduction is not meant to fully cover proptest but rather to give a quick and practical overview of its features. To learn more about it, you should probably read [the proptest documentation](https://altsysrq.github.io/rustdoc/proptest/1.0.0/proptest/index.html).
```

2021-11-25 12:32 UTC, dzmitry-lahoda submitted a review, later dismissed

2021-11-26 09:33 UTC, hussein-aitlahcen commented
> Besides correcting some nits, content LGTM.

Fixed :)

2021-11-26 12:25 UTC, andor0 commented on docs/proptest.md
> +    // Declare that every test within this macro should be executed 10_000 times (new random input each time) to pass.
can use a tab before this line instead of spaces to align with the lines below.

2021-11-26 12:25 UTC, andor0 commented on docs/proptest.md
> +       // recall that this function we be executed 10_000 times when running `cargo test`
can use a tab before those lines instead of spaces to align with the lines below.

2021-11-26 12:25 UTC, andor0 commented on docs/proptest.md
> +    // assume that the minimum useful (or even valid for the property) amount is 0x1337
Can use a tab before this line instead of spaces to align with the lines below.

2021-11-26 16:22 UTC, andor0 approved these changes

2021-11-27 11:40 UTC, hussein-aitlahcen commented
@Br1ght0ne can you review the changes please

2021-11-27 11:45 UTC, Br1ght0ne approved these changes

2021-11-27 11:49 UTC, merged