picasso composable centauri clients build and runs
ComposableFi/composable pull request #3324
Opened 2023-03-27 19:14 UTC by dzmitry-lahoda

**Picasso Composable hyperspace runs and DOT transfered**

- updated centauri to version without beefy
- hyperspace image and binary with patched clients of picasso and composvble
- updated relay runtime (allowed to use exact version composable depends on)
- deleted dali runtime from hyperspace
- made chains explicit in devnet configs to prevent config errors
- tuned debug prameters for hyperspace and devnet rust builds
- split out substrate rust build parameters more

2023-03-28 11:36 UTC, blasrodri commented on devnets/specs/centauri.nix
> +                restartPolicy = "no";
why did you change the restart policy?

2023-03-28 11:37 UTC, blasrodri commented on devnets/specs/centauri.nix
> +                dependsOn = dependsOnCreateConnection;
```suggestion
                dependsOn = dependsOnCreateChannels;
```

2023-04-02 21:53 UTC, blasrodri approved these changes

2023-04-04 17:39 UTC, blasrodri commented on devnets/all.nix
> +          devnet-b = packages.zombienet-picasso-centauri-b;
do you want to merge this? Picasso<>Picasso

2023-04-05 14:42 UTC, andresmechali commented on inputs/paritytech/polkadot.nix
> +            cp $src $out/lib/rococo_runtime.compact.compressed.wasm
shouldn't this be `rococo_runtime-v9360.compact.compressed.wasm`?

2023-04-06 17:01 UTC, blasrodri commented on inputs/paritytech/zombienet/default.nix
> +          "info,runtime=debug,parachain=trace,cumulus-collator=trace,aura=trace,xcm=trace,pallet_ibc=trace,hyperspace=trace,hyperspace_parachain=trace,ics=trace,ics::routing=trace,ics::channel=trace"
do you want to merge with all logs on trace?

2023-04-06 17:01 UTC, blasrodri approved these changes

2023-04-07 10:53 UTC, andresmechali approved these changes

2023-04-07 12:10 UTC, kkast requested changes

2023-04-07 12:10 UTC, kkast commented on code/parachain/runtime/primitives/src/topology.rs
> +				decimals: Some(10),
in the migrated dot we set decimals to 12

2023-04-07 12:10 UTC, kkast commented on code/parachain/runtime/primitives/src/topology.rs
> +				ratio: Some(rational!(2143 / 100_000_000)),
this is also different from migrated dot on composable 
existential_deposit: 214_300_000,
ratio: Some(rational!(2143 / 1_000_000))

2023-04-07 12:10 UTC, kkast commented on code/parachain/runtime/primitives/src/topology.rs
> +				ratio: Some(rational!(375 / 1_000_000_000)),
in picasso usdt id is 130 and parameters:
existential_deposit: 1500,
ratio: Some(rational!(15 / 1_000_000_000)),

2023-04-07 12:10 UTC, kkast commented on code/parachain/runtime/primitives/src/topology.rs
> +				decimals: Some(10),
decimals: Some(12),
existential_deposit: 214_300_000,

2023-04-07 12:10 UTC, kkast commented on code/parachain/runtime/primitives/src/topology.rs
> +				ratio: Some(rational!(15 / 1_000_000_000)),
in picasso usdt id is 130 and parameters:
existential_deposit: 1500,
ratio: Some(rational!(15 / 1_000_000_000)),

2023-04-07 13:24 UTC, kkast approved these changes

2023-04-07 15:47 UTC, blasrodri commented on code/Cargo.toml
> +ibc = { git = "https://github.com/dzmitry-lahoda-forks/centauri", rev = "15b72401a8292f248c2f3afe1e29cf83bf359c36", default-features = false }
why not use Centauri?

2023-04-07 17:29 UTC, merged