Add MinAnswerBound in pallet-oracle #PICA-324
ComposableFi/composable pull request #3389
Opened 2023-04-11 16:26 UTC by obsessed-cake

2023-04-11 16:26 UTC, KaiserKarel commented
Task linked: [PICA-324 BUG - Malicious Oracle can manually submit price to change the price of asset on chain and not gets slashed](https://app.clickup.com/t/20465559/PICA-324)

2023-04-11 17:11 UTC, kkast requested changes

2023-04-11 19:27 UTC, obsessed-cake commented on code/parachain/frame/oracle/src/tests.rs
>  			Validated::new(5).unwrap(),
I returned 1.
There is the test for 3 answers below.

2023-04-12 18:02 UTC, kkast approved these changes

2023-04-12 20:26 UTC, andresmechali approved these changes

2023-04-14 07:52 UTC, kkast approved these changes
Lgtm

2023-04-14 07:54 UTC, merged