Centauri-updates
ComposableFi/composable pull request #3461
Opened 2023-04-20 16:53 UTC by JafarAz

- Updated Centauri content with the latest architecture, diagrams, content and more. 

- Aped a few more miscellaneous items.

- Will update sidebars.js in another PR once this PR is approved

2023-04-20 17:41 UTC, blasrodri commented on docs/docs/codespaces/getting-started.md
> +**If you are not yet part of the ComposableFi GitHub organization, create a ticket with R2D2 in the composable
Does this exist?

2023-04-20 17:43 UTC, blasrodri commented on docs/docs/products/centauri/Dotsama-ibc.md
> +The first implementation of Centauri will be between [Kusama](https://kusama.network/) and [Polkadot](https://polkadot.network/) via Picasso and Composable. This is a significant development because
Present

2023-04-20 17:44 UTC, blasrodri commented on docs/docs/products/centauri/cosmos11-BEEFY-COSMOS-IBC-light-client.md
> +Composable is performing a total of 8 PRs to core BEEFY subsystems in both the runtime and Substrate client, pending further review by the Substrate bridges team. Some are listed below:
I would remove this @0xBrainjar2

2023-04-20 17:45 UTC, blasrodri submitted a review, later dismissed

2023-04-20 17:47 UTC, JafarAz commented on docs/docs/codespaces/getting-started.md
> +**If you are not yet part of the ComposableFi GitHub organization, create a ticket with R2D2 in the composable
yessir still exists

2023-04-20 17:50 UTC, 0xBrainjar2 commented on docs/docs/products/centauri/cosmos11-BEEFY-COSMOS-IBC-light-client.md
> +Composable is performing a total of 8 PRs to core BEEFY subsystems in both the runtime and Substrate client, pending further review by the Substrate bridges team. Some are listed below:
agree

2023-04-20 17:52 UTC, 0xBrainjar2 requested changes

2023-04-20 17:52 UTC, 0xBrainjar2 commented on docs/docs/products/centauri-overview.md
> +Centauri is a decentralized transfer protocol that will facilitate trustless cross-ecosystem communication among various blockchains, including Polkadot, Kusama, Ethereum, NEAR, and Cosmos, using the
is an extension of the IBc protocol

2023-04-20 17:52 UTC, 0xBrainjar2 commented on docs/docs/products/centauri-overview.md
> +Centauri leverages and expands upon the existing Inter-Blockchain Communication Protocol (IBC) beyond Cosmos. The IBC protocol previously allowed for trustless bridging between Cosmos SDK chains; how
are the first

2023-04-20 17:52 UTC, 0xBrainjar2 commented on docs/docs/products/centauri-overview.md
> +- built upon light clients that communicate with each other
light client verification

2023-04-20 18:01 UTC, 0xBrainjar2 approved these changes

2023-04-24 20:51 UTC, 0xBrainjar2 approved these changes

2023-04-24 20:52 UTC, merged