minor-docs-edit
ComposableFi/composable pull request #3626
Opened 2023-05-18 17:00 UTC by JafarAz

- [x] PR title is my best effort to provide summary of changes and has clear text to be part of release notes 
- [x] I marked PR by `misc` label if it should not be in release notes
- [ ] I have linked Zenhub/Github or any other reference item if one exists
- [ ] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [x] I waited and did best effort for `pr-workflow-check / draft-release-check` to finish with success(green check mark) with my changes
- [x] I have added at least one reviewer in reviewers list
- [ ] I tagged(@) or used other form of notification of one person who I think can handle best review of this PR

2023-05-18 17:04 UTC, blasrodri commented on docs/docs/products/centauri/Dotsama-ibc.md
> +The fees for bridging via Centauri is paid by utilizing the tokens being transferred, which have a value of $10.
in case there's a pool on Pablo. Otherwise we resort to .4%

2023-05-18 17:04 UTC, blasrodri requested changes
Please update based on my feedback

2023-05-18 18:02 UTC, blasrodri approved these changes

2023-05-19 04:58 UTC, dzmitry-lahoda commented
seems ai comments are garbage. will of. will rebase on main to check to work.

2023-05-21 16:49 UTC, dzmitry-lahoda submitted a review, later dismissed

2023-05-24 21:41 UTC, merged