vj/coverage ci
ComposableFi/composable pull request #445
Opened 2022-01-05 05:49 UTC by aettran

Adding code coverage with CI

2022-01-05 06:04 UTC, ComposableFiB0t commented
Task linked: [CU-1tt5q2a Require coverage to not decrease to pass CI](https://app.clickup.com/t/1tt5q2a)

2022-01-05 11:40 UTC, KaiserKarel requested changes
Please remove usage of actions-rs, as we'd need to manually update every toolchain input in CI whenever we upgrade rust versions

2022-01-05 16:23 UTC, aettran commented on .github/workflows/check.yml
> +          components: llvm-tools-preview
action-rs is removed

2022-01-06 10:54 UTC, dzmitry-lahoda approved these changes

2022-01-06 13:18 UTC, merged