Feature/simnode workflow
ComposableFi/composable pull request #461
Opened 2022-01-09 20:33 UTC by haroldsphinx

- Add backup script to CI
- Add workflow step to check simonode test

2022-01-09 20:45 UTC, seunlanlege commented on .github/workflows/check.yml
> +          ./target/release/simnode --chain=picasso --base-path=/tmp/db --wasm-runtime-overrides=./target/release/picasso_runtime.compact.wasm --pruning=archive --execution=wasm
I think this should refer to a folder such that this is the only wasm file in that folder.

2022-01-10 05:20 UTC, seunlanlege commented on .github/workflows/picashot.yml
> +name: Check Runtime
```suggestion
name: Nightly backup
```

2022-01-10 07:40 UTC, KaiserKarel commented on .github/workflows/check.yml
> +          toolchain: stable
We've added a toolchain.toml, which pins the rust toolchain we're using. actions-rs does not support that yet, so you'll have to manually install rustup + cargo.

2022-01-10 12:25 UTC, KaiserKarel commented on .github/workflows/check.yml
> +          SKIP_WASM_BUILD=1 /home/runner/.cargo/bin/cargo check --all --benches
Can we add cargo to the path, to abstract how the actual runner is configured?

2022-01-10 12:26 UTC, KaiserKarel commented on .github/workflows/check.yml
> +          toolchain: stable
So we still need to remove this right?

2022-01-10 12:27 UTC, KaiserKarel commented on .github/workflows/client-release.yml
> +        args: --release --bins
This also won't respect the toolchain.toml, meaning that tests are not run vs the same version of rustc as the final build

2022-01-10 12:28 UTC, KaiserKarel requested changes
Would be good to add cargo to the path, as well as removing actions-rs

2022-01-10 12:30 UTC, KaiserKarel approved these changes
After discussing offline, we decided to add the feedback in a later PR

2022-01-10 12:41 UTC, seunlanlege approved these changes

2022-01-10 12:42 UTC, merged

2022-01-10 12:48 UTC, nimboya approved these changes