Add few more test for dex.
ComposableFi/composable pull request #690
Opened 2022-02-28 14:42 UTC by vivekvpandya

Add few more test for dex.
Add extrinsics for add/remove_liquidity().
Update benchmarks.

2022-02-28 15:10 UTC, KaiserKarel commented on frame/curve-amm/src/tests.rs
> +		assert!(lp > 0_u128);
Can we assert that we received the correct amount?

2022-02-28 15:13 UTC, KaiserKarel commented on frame/uniswap-v2/src/lib.rs
> +			let _ = <Self as CurveAmm>::add_liquidity(
Why CurveAmm? Should we rename the trait to just AMM?

2022-02-28 15:14 UTC, KaiserKarel requested changes
Would be good to check that the obtained LP amount is correct

2022-02-28 15:14 UTC, KaiserKarel commented on frame/uniswap-v2/src/lib.rs
> +			let _ = <Self as CurveAmm>::add_liquidity(
Probably good for a second PR

2022-03-01 14:31 UTC, hussein-aitlahcen submitted a review, later dismissed
Thanks for adding a bunch of tests, next step is to add some proptests.

2022-03-04 11:04 UTC, dzmitry-lahoda commented on frame/curve-amm/src/benchmarking.rs
> +  }: _(RawOrigin::Signed(owner), pool_id, lp_amount, (0_u128).into(), (0_u128).into())
does this test handles error to remove? so if remove will fail, benchmark with fail?

2022-03-04 11:04 UTC, dzmitry-lahoda commented on frame/curve-amm/src/benchmarking.rs
> +  }: _(RawOrigin::Signed(owner), pool_id, initial_usdc, initial_usdt, 0.into(), false)
does this test handles error case?

2022-03-04 11:07 UTC, dzmitry-lahoda commented on frame/curve-amm/src/tests.rs
> +		let bob_usdc = 1000 * unit;
may be split into 2 tests?

2022-03-04 11:07 UTC, dzmitry-lahoda commented on frame/curve-amm/src/tests.rs
> +//
// non needed
// -> ///

2022-03-04 11:08 UTC, dzmitry-lahoda commented on frame/uniswap-v2/src/lib.rs
> +		/// Add liquidity to a stable-swap pool.
wrong comment

2022-03-04 11:27 UTC, KaiserKarel approved these changes

2022-03-04 12:56 UTC, dzmitry-lahoda approved these changes

2022-03-04 13:12 UTC, hussein-aitlahcen approved these changes

2022-03-04 13:13 UTC, merged