Amp can not be zero
ComposableFi/composable pull request #725
Opened 2022-03-07 15:08 UTC by vivekvpandya

2022-03-07 16:57 UTC, KaiserKarel commented on frame/curve-amm/src/lib.rs
> +		AmpFactorMustBeGraterThanZero,
```suggestion
		AmpFactorMustBeGreaterThanZero,
```

2022-03-07 16:58 UTC, KaiserKarel requested changes
Just the typo fix

2022-03-08 12:09 UTC, KaiserKarel submitted a review, later dismissed

2022-03-08 12:30 UTC, dzmitry-lahoda approved these changes

2022-03-08 12:56 UTC, KaiserKarel approved these changes

2022-03-08 13:03 UTC, dzmitry-lahoda approved these changes

2022-03-08 13:04 UTC, merged