update download path from github releases
ComposableFi/composable pull request #854
Opened 2022-04-07 13:47 UTC by nimboya

## Issue
https://app.clickup.com/t/25k3rrm

## Description
Update pipeline to fix Docker image issues

## Checklist

- [x] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [x] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

2022-04-07 13:48 UTC, composable-sre requested changes
This pull request does not contain a valid label. Please add one of the following labels: `['major', 'minor', 'patch']`

2022-04-07 13:48 UTC, composable-sre approved these changes

2022-04-07 13:49 UTC, composable-sre approved these changes

2022-04-08 12:37 UTC, haroldsphinx approved these changes

2022-04-08 15:08 UTC, nimboya commented on docker/Dockerfile
> +RUN wget https://github.com/ComposableFi/composable/releases/download/v${VERSION}/composable
this will solve the issue

2022-04-08 15:11 UTC, merged