Docker update
ComposableFi/composable pull request #868
Opened 2022-04-11 14:25 UTC by nimboya

## Issue
* https://app.clickup.com/t/25k3rrm

## Description
* Allow manual workflow run

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

2022-04-11 14:25 UTC, composable-sre requested changes
This pull request does not contain a valid label. Please add one of the following labels: `['major', 'minor', 'patch']`

2022-04-11 14:29 UTC, composable-sre approved these changes

2022-04-14 08:47 UTC, haroldsphinx submitted a review, later dismissed

2022-04-14 09:04 UTC, composable-sre approved these changes

2022-04-14 09:05 UTC, merged