[CU-20185x7] Add integration test mosaic implementation.
ComposableFi/composable pull request #873
Opened 2022-04-12 11:04 UTC by Juliansv

2022-04-12 11:04 UTC, ComposableFiB0t commented
Task linked: [CU-20185x7 Mosaic Pallet Integration Tests](https://app.clickup.com/t/20185x7)

2022-04-12 17:10 UTC, Dom-Roth requested changes
~~There is a type definition missing for `PalletMosaicDecayLinearDecayer`, please add it to `runtime-tests/src/types/interfaces/crowdloanRewards/definitions.ts`. Else the tests won't run.
You probably already added it but didn't commit.~~

NVM i was on an old version!

2022-04-12 18:40 UTC, Dom-Roth requested changes
Looks really good so far! A few tweaks, as well as that weird compile issue, and we're ready to go.

2022-04-12 18:40 UTC, Dom-Roth commented on integration-tests/runtime-tests/test/tests/mosaic/mosaicTests.ts
> +            this.timeout(2*60*1000);
```suggestion
            this.timeout(5*60*1000);
```
Please increase the timeout a bit. It seems to occasionally fail therefore.

2022-04-12 18:40 UTC, Dom-Roth commented on integration-tests/runtime-tests/test/tests/mosaic/mosaicTests.ts
> +            expect(relayerInfo.unwrap().relayer.next.toJSON().account).to.be.equal(api.createType('AccountId32', newRelayerWallet.address).toString());
This only compiles if the code is compiled without type checking cause the linter seems to block this. 
I couldn't get it quickly fixed. We can try on this together tomorrow.

```
> tsc -p . --declaration

test/tests/mosaic/mosaicTests.ts:200:41 - error TS2339: Property 'relayer' does not exist on type 'PalletMosaicRelayerStaleRelayer'.

200             expect(relayerInfo.unwrap().relayer.next.toJSON().account).to.be.equal(api.createType('AccountId32', newRelayerWallet.address).toString());
                                            ~~~~~~~


Found 1 error in test/tests/mosaic/mosaicTests.ts:200
```

2022-04-12 18:40 UTC, Dom-Roth commented on integration-tests/runtime-tests/test/tests/mosaic/mosaicTests.ts
> +import { doesNotMatch } from 'assert';
A lot of unused imports, can be reduced to:
```suggestion
import { expect } from 'chai';
import testConfiguration from './test_configuration.json';
import { sendAndWaitForSuccess } from '@composable/utils/polkadotjs';
import {KeyringPair} from "@polkadot/keyring/types";
import { mintAssetsToWallet } from '@composable/utils/mintingHelper';
import {
    CommonMosaicRemoteAssetId,
    OrmlTokensAccountData,
    PalletMosaicDecayBudgetPenaltyDecayer,
    PalletMosaicNetworkInfo
} from "@composable/types/interfaces";
```

2022-04-19 18:11 UTC, Dom-Roth approved these changes

2022-04-20 10:10 UTC, kollegian approved these changes
LGTM

2022-04-20 12:24 UTC, Dom-Roth requested changes
Commits need to be signed!

2022-04-20 18:54 UTC, Dom-Roth approved these changes

2022-04-20 18:57 UTC, kollegian approved these changes
LGTM

2022-04-20 19:30 UTC, merged